// constants/action-types.js

export const ActionTypes = {
  ADD_USER:"ADD_USER",

  ADD_TO_CART:"ADD_TO_CART",
  REMOVE_CART_PRODUCT:"REMOVE_CART_PRODUCT",
  HANDLE_QUANTITY:"HANDLE_QUANTITY",

  SET_PRODUCTS: "SET_PRODUCTS",
  SELECTED_PRODUCT: "SELECTED_PRODUCT",
  REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",

  SET_CART: "SET_CART",
  SET_CART_PRODUCTS: "SET_CART_PRODUCTS",
  SELECTED_CART_PRODUCT: "SELECTED_CART_PRODUCT",
  REMOVE_CART_SELECTED_PRODUCT: "REMOVE_CART_SELECTED_PRODUCT",
};
